[package]
name = "signal-hook"
version = "0.1.16"
authors = [
    "Michal 'vorner' Vaner <vorner@vorner.cz>",
    "Thomas Himmelstoss <thimm@posteo.de>",
]
description = "Unix signal handling"
documentation = "https://docs.rs/signal-hook"
repository = "https://github.com/vorner/signal-hook"
readme = "README.md"
keywords = ["signal", "unix", "daemon"]
license = "Apache-2.0/MIT"
edition = "2018"

[badges]
travis-ci = { repository = "vorner/signal-hook" }
maintenance = { status = "actively-developed" }

[workspace]
members = [
    "./",
    "signal-hook-registry",
    "signal-hook-tokio",
    "signal-hook-mio",
]

[dependencies]
libc = "~0.2.80"
signal-hook-registry = { version = "~1.2", path = "signal-hook-registry" }

[dev-dependencies]
version-sync = "~0.8"
serial_test = "~0.5"


[package.metadata.docs.rs]
all-features = true
