[package]
name = "signal-hook-mio"
version = "0.1.0"
authors = [
    "Michal 'vorner' Vaner <vorner@vorner.cz>",
    "Thomas Himmelstoss <thimm@posteo.de>",
]

description = "MIO support for signal-hook"
documentation = "https://docs.rs/signal-hook-mio"
readme = "README.md"
repository = "https://github.com/vorner/signal-hook"
keywords = ["signal", "unix", "mio"]
license = "Apache-2.0/MIT"

edition = "2018"

[badges]
travis-ci = { repository = "vorner/signal-hook" }
maintenance = { status = "actively-developed" }

[features]
support-v0_6 = ["mio-0_6", "mio-uds"]
support-v0_7 = ["mio-0_7"]

[dependencies]
# libc = "~0.2"
libc = { version = "0.2.79", git = "https://github.com/gremlin/libc.git", branch = "update-musl-siginfo" }
signal-hook = { version = "~0.1", path = ".." }
mio-0_7 = { package = "mio", version = "~0.7", features = ["os-util", "uds"], optional = true}
mio-0_6 = { package = "mio", version = "~0.6", optional = true}
mio-uds = { version = "~0.6", optional = true}

[dev-dependencies]
mio-0_7 = { package = "mio", version = "~0.7", features = ["os-util", "os-poll", "uds"] }
version-sync = "~0.8"
serial_test = "~0.5"
